"""Deterministic, offline 720p MP4 export from a WAV and schema-1 score.

Optional dependencies: Pillow and FFmpeg with libx264/AAC support.
"""
import argparse
from bisect import bisect_right
import json
import math
from pathlib import Path
import shutil
import subprocess
import tempfile
import wave

WIDTH, HEIGHT = 1280, 720


def load_score(path):
    score = json.loads(Path(path).read_text(encoding='utf-8-sig'))
    if not isinstance(score, dict) or score.get('schema_version') != 1 or score.get('timebase') != 'arranged_audio_seconds':
        raise ValueError('Use a schema-1 score generated by pd_musicus.py')
    duration = score.get('duration_s')
    if not isinstance(duration, (int, float)) or not math.isfinite(duration) or not 0 < duration <= 600:
        raise ValueError('Score duration must be between 0 and 600 seconds')
    events = score.get('timeline')
    if not isinstance(events, list) or len(events) > 100000:
        raise ValueError('Invalid timeline')
    previous = -1
    for event in events:
        if not isinstance(event, dict):
            raise ValueError('Timeline events must be objects')
        t = event.get('at_s')
        if not isinstance(t, (int, float)) or not math.isfinite(t) or not previous <= t <= duration or t < 0 or not isinstance(event.get('label'), str):
            raise ValueError('Timeline events must be ordered and contain valid times and labels')
        previous = t
        data = event.get('data', {})
        if not isinstance(data, dict):
            raise ValueError('Invalid event data')
        for key in ('actual_power_W', 'actual_voltage_V', 'actual_current_A', 'voltage_V', 'current_A', 'target_voltage_V'):
            if key in data and (not isinstance(data[key], (int, float)) or not math.isfinite(data[key]) or data[key] < 0):
                raise ValueError(f'Invalid {key}')
        if 'statuses' in data and (not isinstance(data['statuses'], list) or not all(isinstance(s, str) for s in data['statuses'])):
            raise ValueError('Invalid measurement statuses')
    return score


class Timeline:
    def __init__(self, score):
        self.events = score['timeline']
        self.times = [e['at_s'] for e in self.events]
        self.measurements = []
        data = None
        for e in self.events:
            if e.get('kind') in ('hard_reset', 'soft_reset') or str(e.get('status', '')).startswith('VBUS'):
                data = None
            elif 'data' in e:
                data = e['data']
            self.measurements.append(data)

    def at(self, time):
        index = bisect_right(self.times, time + 1 / 44100) - 1
        return index, self.events[index] if index >= 0 else None, self.measurements[index] if index >= 0 else None


def font_path(explicit=None):
    if explicit:
        if not Path(explicit).is_file():
            raise ValueError('Font file not found')
        return str(explicit)
    candidates = ('C:/Windows/Fonts/segoeui.ttf', '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
                  '/System/Library/Fonts/Supplemental/Arial.ttf')
    return next((p for p in candidates if Path(p).is_file()), None)


class VideoFrames:
    def __init__(self, score, title='PD musicus', font=None):
        try:
            from PIL import Image, ImageDraw, ImageFont
        except ImportError as exc:
            raise ValueError('Video export needs Pillow: python -m pip install Pillow') from exc
        self.Image, self.ImageDraw, self.ImageFont = Image, ImageDraw, ImageFont
        self.fontfile = font_path(font)
        self.fonts = {}
        self.score, self.timeline, self.title = score, Timeline(score), title

    def font(self, size):
        if size not in self.fonts:
            self.fonts[size] = self.ImageFont.truetype(self.fontfile, size) if self.fontfile else self.ImageFont.load_default(size=size)
        return self.fonts[size]

    def frame(self, time):
        image = self.Image.new('RGB', (WIDTH, HEIGHT), '#101117')
        draw = self.ImageDraw.Draw(image)
        index, event, data = self.timeline.at(time)
        data = data or {}
        power = data.get('actual_power_W')
        intensity = min(1, max(0, (power or 0)/240))
        accent = '#ffac85' if intensity > .75 else '#b6a1ff'
        muted = '#999aaf'
        def text(x,y,value,size=18,color='#eeeeF5',max_width=None):
            value = str(value)
            if max_width:
                while size > 11 and draw.textlength(value, font=self.font(size)) > max_width:
                    size -= 1
                if draw.textlength(value, font=self.font(size)) > max_width:
                    while value and draw.textlength(value+'…',font=self.font(size)) > max_width:
                        value = value[:-1]
                    value += '…'
            draw.text((x,y),value,font=self.font(size),fill=color)
        def box(bounds, fill='#191b25', outline='#30313e'):
            draw.rounded_rectangle(bounds, radius=16, fill=fill, outline=outline, width=1)
        def number(value, digits=3):
            return f'{value:.{digits}f}' if isinstance(value,(int,float)) else '—'
        def clock(t):
            return f'{int(t)//60:02}:{int(t)%60:02}'
        text(40,22,'PD musicus',28)
        text(225,33,'LISTEN TO THE CONVERSATION',12,muted)
        text(960,31,f"{self.score.get('mode','music').upper()} / {self.score.get('bpm','—')} BPM",14,muted)
        draw.line((40,72,1240,72),fill='#30313e')
        text(40,87,self.title,25,max_width=1150)
        reset = event and event.get('kind') in ('hard_reset','soft_reset')
        failed = event and any(s.startswith('failed') for s in event.get('data',{}).get('statuses',[]))
        box((40,136,890,484), '#251d2a' if reset or failed else '#191b25',accent if reset else '#30313e')
        box((910,136,1240,484))
        text(65,155,'THE CONVERSATION',12,accent)
        text(750,155,f"{max(0,index+1)} / {len(self.timeline.events)}",12,muted)
        kind = event.get('kind','protocol') if event else 'prelude'
        packet = event and kind == 'protocol' and event.get('sop') == 'SOP' and not str(event.get('status','')).startswith('VBUS')
        text(130,198,'SOURCE',18,accent if packet and event.get('role')=='SRC' else muted)
        text(690,198,'SINK',18,accent if packet and event.get('role')=='SNK' else muted)
        draw.line((250,218,650,218),fill='#655770',width=2)
        if packet and event.get('role') in ('SRC','SNK'):
            right = event['role']=='SRC'
            end = 640 if right else 260
            draw.polygon([(end,218),(end-12 if right else end+12,211),(end-12 if right else end+12,225)],fill=accent)
            age = time-event['at_s']
            if 0 <= age < .5:
                x = 250+400*age/.5 if right else 650-400*age/.5
                draw.ellipse((x-5,213,x+5,223),fill=accent)
        text(65,257,kind.replace('_',' ').upper(),12,accent)
        text(65,282,event['label'] if event else 'Prelude',39,max_width=790)
        voltage = data.get('voltage_V',data.get('target_voltage_V'))
        detail = 'Accompaniment before the first event.'
        if event:
            if kind=='measurement':
                detail = f"{' / '.join(data.get('statuses', []))} · Target {number(voltage,1)} V"
            else:
                route = 'Source → Sink' if event.get('role')=='SRC' else 'Sink → Source' if event.get('role')=='SNK' else ''
                if event.get('sop')!='SOP': route='Cable / alternate SOP'
                detail = f"{event.get('sop','')}  {route}"
                if voltage is not None: detail += f"  ·  Request {voltage:.1f} V / {number(data.get('current_A'),2)} A"
        text(65,338,detail,17,muted,max_width=790)
        # Decorative power-driven pulse, not a sampled audio spectrum.
        for i in range(68):
            height = 5+(12+28*intensity)*abs(math.sin(time*(4+6*intensity)+i*.65))*math.sin((i+1)/69*math.pi)
            x=70+i*11.5
            draw.rounded_rectangle((x,409-height/2,x+4,409+height/2),radius=2,fill=accent)
        reference = f"PD row {event['source_row']}" if event and 'source_row' in event else f"ASD case {event['label']}" if event else 'Prelude'
        text(65,451,reference,12,muted,max_width=540)
        text(664,451,'ARRANGED AUDIO TIME',12,muted)
        text(934,156,'MEASURED POWER',12,accent)
        text(934,188,number(power,1),60,max_width=238)
        text(1183,229,'W',20,muted)
        draw.rounded_rectangle((936,282,1213,290),radius=4,fill='#373744')
        if intensity>0: draw.rounded_rectangle((936,282,936+277*intensity,290),radius=4,fill=accent)
        text(936,300,'0 W',11,muted);text(1173,300,'240 W',11,muted)
        text(936,331,'VOLTAGE',11,muted);text(1085,331,'CURRENT',11,muted)
        text(936,353,f"{number(data.get('actual_voltage_V'))} V",22,max_width=142)
        text(1085,353,f"{number(data.get('actual_current_A'))} A",22,max_width=138)
        mood = 'NO MEASUREMENT' if power is None else 'FULL POWER' if power>200 else 'BUILDING ENERGY' if power>100 else 'GENTLE' if power<=30 else 'IN MOTION'
        text(936,405,mood,14,accent)
        text(936,442,'Measurement point, not a live meter.',11,muted)
        duration=self.score['duration_s']
        text(40,507,'EVENT TRAIL',12,muted)
        start=max(0,min(index-1,len(self.timeline.events)-3))
        for j,e in enumerate(self.timeline.events[start:start+3]):
            x=40+j*405;current=start+j==index
            box((x,533,x+390,618),'#30263e' if current else '#191b25',accent if current else '#30313e')
            text(x+16,544,'NOW' if current else 'PREVIOUS' if start+j<index else 'UP NEXT',10,accent if current else muted)
            text(x+16,563,e['label'],20,max_width=355)
            text(x+16,595,clock(e['at_s']),11,muted)
        draw.rounded_rectangle((40,645,1240,650),radius=2,fill='#373744')
        if time>0: draw.rounded_rectangle((40,645,40+1200*min(1,time/duration),650),radius=2,fill=accent)
        text(40,674,'Musical timing · Synthetic instruments · Power-driven visuals',12,muted)
        text(1090,672,f'{clock(time)} / {clock(duration)}',17)
        return image


def export_video(wav_path, score_path, out, fps=30, title='PD musicus', font=None, ffmpeg='ffmpeg', overwrite=False):
    wav_path, score_path, out = map(Path,(wav_path,score_path,out))
    if out.suffix.lower()!='.mp4': raise ValueError('Output must end in .mp4')
    if out.resolve() in (wav_path.resolve(),score_path.resolve()): raise ValueError('Output must not replace an input')
    if out.exists() and not overwrite: raise ValueError('Output exists; use --overwrite or another name')
    if fps not in (24,30,60): raise ValueError('FPS must be 24, 30, or 60')
    score=load_score(score_path)
    with wave.open(str(wav_path),'rb') as audio:
        duration=audio.getnframes()/audio.getframerate()
        if abs(duration-score['duration_s'])>.05: raise ValueError('WAV duration does not match the score')
    encoder=shutil.which(str(ffmpeg))
    if not encoder: raise ValueError('FFmpeg not found; install it or supply --ffmpeg PATH')
    frames=VideoFrames(score,title,font)
    out.parent.mkdir(parents=True,exist_ok=True)
    count=math.ceil(duration*fps)
    # Encode to a sibling temporary file so a failed export cannot replace a good video.
    with tempfile.TemporaryDirectory(prefix='.musicus-video-',dir=out.parent) as temp:
        encoded=Path(temp)/'render.mp4'
        cmd=[encoder,'-hide_banner','-loglevel','error','-y','-f','rawvideo','-pixel_format','rgb24',
             '-video_size',f'{WIDTH}x{HEIGHT}','-framerate',str(fps),'-i','pipe:0','-i',str(wav_path.resolve()),
             '-map','0:v:0','-map','1:a:0','-c:v','libx264','-preset','fast','-crf','20','-pix_fmt','yuv420p',
             '-c:a','aac','-b:a','192k','-t',f'{duration:.9f}','-movflags','+faststart',str(encoded)]
        with (Path(temp)/'encoder.log').open('w+b') as log:
            proc=subprocess.Popen(cmd,stdin=subprocess.PIPE,stdout=subprocess.DEVNULL,stderr=log)
            try:
                for i in range(count):
                    proc.stdin.write(frames.frame(i/fps).tobytes())
                    if i%(fps*5)==0: print(f'Rendering {i/fps:.0f}/{duration:.1f}s',flush=True)
                proc.stdin.close()
                code=proc.wait()
                if code:
                    log.seek(0)
                    raise ValueError('FFmpeg failed: '+log.read().decode('utf-8',errors='replace')[-2000:])
            except BaseException as exc:
                if proc.poll() is None:
                    proc.terminate();proc.wait()
                if proc.stdin and not proc.stdin.closed:
                    try:
                        proc.stdin.close()
                    except BrokenPipeError:
                        pass
                if isinstance(exc,BrokenPipeError):
                    log.seek(0)
                    raise ValueError('FFmpeg failed: '+log.read().decode('utf-8',errors='replace')[-2000:]) from exc
                raise
        encoded.replace(out)
    return dict(path=str(out.resolve()),duration_s=duration,fps=fps,frames=count,width=WIDTH,height=HEIGHT)


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('wav',type=Path)
    parser.add_argument('--score',type=Path,required=True)
    parser.add_argument('--out',type=Path,required=True)
    parser.add_argument('--fps',type=int,choices=(24,30,60),default=30)
    parser.add_argument('--title',default='PD musicus')
    parser.add_argument('--font',type=Path)
    parser.add_argument('--ffmpeg',default='ffmpeg')
    parser.add_argument('--overwrite',action='store_true')
    args=parser.parse_args()
    try:
        print(json.dumps(export_video(args.wav,args.score,args.out,args.fps,args.title,args.font,args.ffmpeg,args.overwrite),indent=2))
    except (ValueError,OSError,wave.Error) as exc:
        parser.exit(1,f'Error: {exc}\n')


if __name__=='__main__': main()
