(function(root){
  'use strict';
  const finite = v => typeof v === 'number' && Number.isFinite(v);
  function validate(score){
    if(!score || score.schema_version !== 1 || score.timebase !== 'arranged_audio_seconds') throw Error('Use a schema 1 score generated by pd_musicus.py.');
    if(!finite(score.duration_s) || score.duration_s <= 0 || score.duration_s > 3600) throw Error('Invalid score duration.');
    if(!Array.isArray(score.timeline) || score.timeline.length > 100000) throw Error('Invalid event timeline.');
    let previous = -1;
    for(const e of score.timeline){
      if(!e || !finite(e.at_s) || e.at_s < previous || e.at_s < 0 || e.at_s > score.duration_s || typeof e.label !== 'string') throw Error('Timeline must contain ordered events with valid times and labels.');
      if(e.source_lines!==undefined&&(!Array.isArray(e.source_lines)||!e.source_lines.every(Number.isInteger)))throw Error('Invalid source line references.');
      if(e.data!==undefined){
        if(!e.data||typeof e.data!=='object'||Array.isArray(e.data))throw Error('Invalid event data.');
        if(e.data.statuses!==undefined&&(!Array.isArray(e.data.statuses)||!e.data.statuses.every(s=>typeof s==='string')))throw Error('Invalid measurement statuses.');
        for(const key of ['actual_power_W','actual_voltage_V','actual_current_A','voltage_V','current_A','target_voltage_V']){
          if(e.data[key]!==undefined&&(!finite(e.data[key])||e.data[key]<0))throw Error('Invalid measurement value.');
        }
      }
      previous=e.at_s;
    }
    return score;
  }
  // Browsers can round a requested seek down by a fraction of an audio sample.
  function indexAt(events,time){let lo=0,hi=events.length;while(lo<hi){const mid=(lo+hi)>>1;if(events[mid].at_s<=time+1/44100)lo=mid+1;else hi=mid;}return lo-1;}
  function stateAt(score,time){
    const index=indexAt(score.timeline,time), event=score.timeline[index]||null;
    let data=null;
    for(let i=index;i>=0;i--){
      const e=score.timeline[i];
      if(e.kind==='hard_reset'||e.kind==='soft_reset'||String(e.status).startsWith('VBUS'))break;
      if(e.data){data=e.data;break;}
    }
    const power=data&&finite(data.actual_power_W)?data.actual_power_W:null;
    return {index,event,data,power,intensity:power===null?0:Math.max(0,Math.min(1,power/240))};
  }
  const api={validate,indexAt,stateAt};
  if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.MusicusTimeline=api;
})(globalThis);
